on:  
  push:  
    branches:  
      - feature/*  
      - fix/*  
  pull_request:  
    branches:  
      - release/**  
      - develop  
    
jobs:    
  build:  
    runs-on: macos-15  
    strategy:  
      matrix:  
        xcodebuild-scheme: ['App']  
          
    steps:  
      - uses: actions/checkout@v4  
      - uses: jdx/mise-action@v2  
      - uses: ruby/setup-ruby@v1  
        with:   
          ruby-version: '3.2.0'  

      - name: Setup Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_16.2.app
              
      - name: Checkout branch  
        uses: actions/checkout@v4
        with:  
          token: ${{ secrets.GIT_BASIC_AUTHORIZATION }}  

      - name: Install Specific Tuist Version    
        run: |
          export TUIST_VERSION="4.35.0"
          bash <(curl -Ls https://install.tuist.io)
          
      - name: Install FastLane   
        uses: ruby/setup-ruby@v1  
        with:  
          ruby-version: '3.2.0'  
      - run: brew install fastlane  

      - name: Check Tuist Version
        run: tuist version

      - name: Tuist Clean Command  
        run: tuist clean  
        
      - name: Tuist Install Command
        run: tuist install
        
      - name: Tuist Generate Command with verbose
        run: tuist generate --no-open

      - name: .env setting
        run: |
          echo "APP_STORE_CONNECT_API_KEY_KEY_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}" >> .env
          echo "APP_STORE_CONNECT_API_KEY_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}" >> .env
          echo "APP_STORE_CONNECT_API_KEY_KEY=${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}" >> .env
          echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}" >> .env
          echo "DISCORD_URL=${{ secrets.DISCORD_URL }}" >> .env
          echo "GIT_BASIC_AUTHORIZATION=${{ secrets.GIT_BASIC_AUTHORIZATION }}" >> .env
          echo "BUNDLE_ID=${{ secrets.BUNDLE_ID }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> .env
          echo "TEAM_ID=${{ secrets.TEAM_ID }}" >> .env
          echo "KEYCHAIN_NAME=${{ secrets.KEYCHAIN_NAME }}" >> .env
          echo "KEYCHAIN_PASSWORD=${{ secrets.KEYCHAIN_PASSWORD }}" >> .env

      - name: fasltane print_date
        run: fastlane print_date

      - name: fastlane discord_webhook should_notify:true
        run: fastlane discord_webhook should_notify:true
        
      - name: fastlane upload_prd_testflight  
        # if: github.event.pull_request.base.ref == 'develop' && github.head_ref == 'feature'  
        env:  
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}  
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}  
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}  
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}  
          DISCORD_URL: ${{secrets.DISCORD_URL}}  
          GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_BASIC_AUTHORIZATION}}
          BUNDLE_ID: ${{secrets.BUNDLE_ID}}  
          APP_NAME: ${{secrets.APP_NAME}}
          APPLE_ID: ${{secrets.APPLE_ID}}  
          TEAM_ID: ${{secrets.TEAM_ID}}  
          KEYCHAIN_NAME: ${{secrets.KEYCHAIN_NAME}}
          KEYCHAIN_PASSWORD: ${{secrets.KEYCHAIN_PASSWORD}}
        run: fastlane github_action_stg_upload_testflight  
